version: '3'
services:
    nginx2:
        image: jokerdab/becadevops:nginx-2.0
        container_name: docker-compose-nginx2
        restart: always
        ports:
          - "8090:80"
        volumes: 
          - .:/usr/share/nginx/html
    nginx3:
        image: jokerdab/becadevops:nginx-3.0
        container_name: docker-compose-nginx3
        restart: always
        ports:
          - "8091:80"
        volumes: 
          - .:/usr/share/nginx/html